### ISSUE TITLE
Overlay disappears when clicking the "get overlay URL" button and Browsersource doesn´t show in OBS

### ISSUE THREAD

**Issue by michaeloeser** [aaronpk/live-chat-overlay#34]
Hi there,

What a great plugin. Just installed it today and it works fine until I click the "get overlay URL" button. The overlay disappears when clicking the "get overlay URL" button and the browsersource doesn´t show in OBS.

Any ideas?

Cheers
Michael

**Comment by aaronpk** [comment]
The overlay disappears from the main window when you click "Get Overlay URL" because it's assumed that you are then bringing in that separate URL into OBS. Copy the URL that appears after you press "Get Overlay URL" and add that into OBS.

**Comment by michaeloeser** [comment]
I did that (copying the URL and bring it to OBS as a browser source) but it shows a black screen in OBS.

**Comment by michaeloeser** [comment]
Ahhh...stupid me. Now it works. Thanks a ton

**Comment by michaeloeser** [comment]
Final question. Are there any "best settings" for the browser source in OBS?

**Comment by aaronpk** [comment]
Definitely set the width and height to 1920x1080. There won't be any sounds so you can leave the "control audio" unchecked. Other than that I leave everything the default. I still need to test if setting a custom frame rate improves performance at all, because sometimes if the computer is busy doing other stuff I've noticed the animations skipping some frames.

**Comment by michaeloeser** [comment]
Thanks a lot
