### ISSUE TITLE
Package as a cross-browser extension

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/live-chat-overlay#5]
Currently this relies on the `chrome.storage` API for saving settings. Need to find a cross-browser way to do that

**Comment by aaronpk** [comment]
This has been published to the firefox store and works fine.

**Comment by yusufipk** [comment]
Hi Aaron,

I use this extension for my weekly live streams and thank you for creating this extension.

I noticed that while this issue is closed, the Firefox version of the extension still has some incomplete features. Specifically, some images appear to be broken in the Firefox version of the app. (#60)

Would it be possible to consider updating the extension to address these cross-browser compatibility issues? It looks like it has been updated 2 years ago. This would greatly improve the user experience for Firefox users.

Thank you for your consideration.
